package io.vertx.jdbcclient;

import io.vertx.codegen.annotations.DataObject;
import io.vertx.codegen.json.annotations.JsonGen;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.sqlclient.PrepareOptions;

/**
 * Options for preparing JDBC statements.
 * <p>
 * This class extends {@link PrepareOptions} and adds JDBC-specific options for controlling auto-generated keys retrieval during statement execution.
 */
@DataObject
@JsonGen(publicConverter = false)
public class JDBCPrepareOptions extends PrepareOptions {

  /**
   * Default value for auto-generated keys retrieval.
   */
  public static final boolean DEFAULT_AUTO_GENERATED_KEYS = true;

  private boolean autoGeneratedKeys;
  private JsonArray autoGeneratedKeysIndexes;

  /**
   * Creates a new instance with default values.
   */
  public JDBCPrepareOptions() {
    this.autoGeneratedKeys = DEFAULT_AUTO_GENERATED_KEYS;
  }

  /**
   * Creates a new instance by copying another instance.
   *
   * @param other the instance to copy
   */
  public JDBCPrepareOptions(JDBCPrepareOptions other) {
    super(other);
    this.autoGeneratedKeys = other.autoGeneratedKeys;
    this.autoGeneratedKeysIndexes = other.autoGeneratedKeysIndexes != null ? other.autoGeneratedKeysIndexes.copy() : null;
  }

  /**
   * Creates a new instance from JSON.
   *
   * @param json the JSON object
   */
  public JDBCPrepareOptions(JsonObject json) {
    super(json);
    JDBCPrepareOptionsConverter.fromJson(json, this);
  }

  /**
   * Creates a JDBC-specific instance from generic prepare options.
   *
   * @param options the generic prepare options
   * @return a new JDBCPrepareOptions instance
   */
  public static JDBCPrepareOptions createFrom(PrepareOptions options) {
    if (options instanceof JDBCPrepareOptions) {
      return (JDBCPrepareOptions) options;
    } else {
      return new JDBCPrepareOptions(options.toJson());
    }
  }

  /**
   * Returns whether auto-generated keys should be retrieved.
   *
   * @return true if auto-generated keys should be retrieved, false otherwise
   */
  public boolean isAutoGeneratedKeys() {
    return autoGeneratedKeys;
  }

  /**
   * Sets whether auto-generated keys should be retrieved.
   * <p>
   * This is particularly useful for Oracle databases where batch operations do not support DML returning clauses for generated keys.
   *
   * @param autoGeneratedKeys true to retrieve auto-generated keys, false to disable
   * @return a reference to this, so the API can be used fluently
   */
  public JDBCPrepareOptions setAutoGeneratedKeys(boolean autoGeneratedKeys) {
    this.autoGeneratedKeys = autoGeneratedKeys;
    return this;
  }

  /**
   * Returns the indexes of auto-generated keys to retrieve.
   *
   * @return the indexes or column names, or null if not set
   */
  public JsonArray getAutoGeneratedKeysIndexes() {
    return autoGeneratedKeysIndexes;
  }

  /**
   * Sets the indexes or column names of auto-generated keys to retrieve.
   * <p>
   * The array can contain either integers (column indexes) or strings (column names).
   *
   * @param autoGeneratedKeysIndexes the indexes or column names
   * @return a reference to this, so the API can be used fluently
   */
  public JDBCPrepareOptions setAutoGeneratedKeysIndexes(JsonArray autoGeneratedKeysIndexes) {
    this.autoGeneratedKeysIndexes = autoGeneratedKeysIndexes;
    return this;
  }
}
