= Vert.x JDBC service

This service allows you to interact with any JDBC compliant database using an asynchronous API from your Vert.x
application.

== Setting up the service

As with other services you can use the service either by deploying it as a verticle somewhere on your network and
interacting with it over the event bus, either directly by sending messages, or using a service proxy, e.g.

Somewhere you deploy it:

[source,java]
----

// Deploy service - can be anywhere on your network
def config = [
  host:"mymysqldb.mycompany"
]
def options = [
  config:config
]

vertx.deployVerticle("io.vertx:jdbc-service", options, { res ->
  if (res.succeeded()) {
  } else {
  }
})

----

Now you can either send messages to it directly over the event bus, or you can create a proxy to the service
from wherever you are and just use that:

[source,java]
----
import io.vertx.groovy.ext.jdbc.JdbcService

def proxy = JdbcService.createEventBusProxy(vertx, "vertx.jdbc")

// Now do stuff with it:

proxy.getConnection({ res ->
  if (res.succeeded()) {

    def connection = res.result()

    connection.query("SELECT * FROM some_table", { res2 ->
      if (res2.succeeded()) {

        def rs = res2.result()
        // Do something with results
      }
    })
  } else {
  }
})

----

Alternatively you can create an instance of the service directly and just use that locally:

[source,java]
----
import io.vertx.groovy.ext.jdbc.JdbcService

def config = [
  host:"mymysqldb.mycompany"
]

def jdbcService = JdbcService.create(vertx, config)

jdbcService.start()


----

If you create an instance this way you should make sure you start it with `link:groovydoc/io/vertx/groovy/ext/jdbc/JdbcService.html#start()[start]`
before you use it.

You can also create a local instance specifying a Java datasource:

[source,java]
----
import io.vertx.groovy.ext.jdbc.JdbcService

def config = [
  host:"mymysqldb.mycompany"
]

def jdbcService = JdbcService.create(vertx, config, myDataSource)

jdbcService.start()


----

However you do it, once you've got your service you can start using it.

== Getting a connection

Use `link:groovydoc/io/vertx/groovy/ext/jdbc/JdbcService.html#getConnection(io.vertx.core.Handler)[getConnection]` to get a connection.

This will return the connection in the handler when one is ready from the pool.

[source,java]
----

// Now do stuff with it:

service.getConnection({ res ->
  if (res.succeeded()) {

    def connection = res.result()

    // Got a connection

  } else {
  }
})


----

Once you've finished with the connection make sure you close it afterwards.

The connection is an instance of `link:groovydoc/io/vertx/groovy/ext/sql/SqlConnection.html[SqlConnection]` which is a common interface used by
more than Vert.x sql service.

You can learn how to use it in the http://foobar[common sql interface] documentation.

== Configuration

Configuration is passed to the service when creating or deploying it.

The following configuration properties generally apply:

`address`:: The address this service should register on the event bus. Defaults to `vertx.jdbc`.
`provider_class`:: The class name of the class actually used to manage the database connections. By default this is
`io.vertx.ext.jdbc.spi.impl.C3P0DataSourceProvider`but if you want to use a different provider you can override
this property and provide your implementation.

Assuming the C3P0 implementation is being used (the default), the following extra configuration properties apply:

`url`:: the JDBC connection URL for the database
`driver_class`:: the class of the JDBC driver
`user`:: the username for the database
`password`:: the password for the database
`max_pool_size`:: the maximum number of connections to pool - default is `15`
`initial_pool_size`:: the number of connections to initialise the pool with - default is `3`
`min_pool_size`:: the minimum number of connections to pool
`max_statements`:: the maximum number of prepared statements to cache - default is `0`.
`max_statements_per_connection`:: the maximum number of prepared statements to cache per connection - default is `0`.
`max_idle_time`:: number of seconds after which an idle connection will be closed - default is `0` (never expire).

If you want to configure any other C3P0 properties, you can add a file `c3p0.properties` to the classpath.

Here's an example of configuring a service:

[source,java]
----
import io.vertx.groovy.ext.jdbc.JdbcService

def config = [
  url:"jdbc:hsqldb:mem:test?shutdown=true",
  driver_class:"org.hsqldb.jdbcDriver",
  max_pool_size:30
]

def service = JdbcService.create(vertx, config)

service.start()

----