= Vert.x JDBC Service

The link:groovydoc/io/vertx/groovy/ext/jdbc/JdbcService.html[`JDBC Service`] is responsible for providing an interface for Vert.x applications that need to interact with
a database using a JDBC driver.

== Getting Started

Since the JDBC service is a service proxy, there are several ways to get started, but the easiest is to just deploy the service
verticle:
[source,{lang}]
----
import io.vertx.groovy.core.Vertx
def vertx = Vertx.vertx();
vertx.deployVerticle("service:io.vertx:vertx-jdbc");

----

and get the service like so:
[source,{lang}]
----
import io.vertx.groovy.ext.jdbc.JdbcService
def service = JdbcService.createEventBusProxy(vertx, "vertx.jdbc");

----

You can also specify configuration options during the deployment.
[source,{lang}]
----
todo
----

This example configures the JDBC service to use a postgres JDBC url in oder to connect to a postgresql database. As long
as the postgresql JDBC driver is on the classpath, the service will be able to connect and interact with the postgresql database.

//TODO: complete docs