CREATE TABLE ANIMAL (
  ID     BIGSERIAL    NOT NULL PRIMARY KEY,
  NAME   VARCHAR(100) NOT NULL UNIQUE,
  IS_PET BOOLEAN      NOT NULL);

INSERT INTO ANIMAL (IS_PET, NAME) VALUES (TRUE, 'dog');
INSERT INTO ANIMAL (IS_PET, NAME) VALUES (TRUE, 'cat');
INSERT INTO ANIMAL (IS_PET, NAME) VALUES (FALSE, 'cow');
